name: flutter_firebase
description: A new Flutter project.

# Prevent publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  # Firebase dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6

  # Other dependencies
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.1.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/koi.png
