// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTJFck3bpZJEMovAku00IEovPFoidVVwI',
    appId: '1:373194371853:web:53211d9b31c0256dcc3644',
    messagingSenderId: '373194371853',
    projectId: 'project-semester4-ce288',
    authDomain: 'project-semester4-ce288.firebaseapp.com',
    storageBucket: 'project-semester4-ce288.firebasestorage.app',
    measurementId: 'G-VY232KTTVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSs-7Whgz7BCM5dxWy5JEwepgu4yQlyKs',
    appId: '1:373194371853:android:50fc3fbd8521ac7acc3644',
    messagingSenderId: '373194371853',
    projectId: 'project-semester4-ce288',
    storageBucket: 'project-semester4-ce288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Uk-Ft5KkQ2rA9m4i3M-ya34FJ1XgJC8',
    appId: '1:373194371853:ios:f390d4042004d9accc3644',
    messagingSenderId: '373194371853',
    projectId: 'project-semester4-ce288',
    storageBucket: 'project-semester4-ce288.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Uk-Ft5KkQ2rA9m4i3M-ya34FJ1XgJC8',
    appId: '1:373194371853:ios:f390d4042004d9accc3644',
    messagingSenderId: '373194371853',
    projectId: 'project-semester4-ce288',
    storageBucket: 'project-semester4-ce288.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTJFck3bpZJEMovAku00IEovPFoidVVwI',
    appId: '1:373194371853:web:51752c903a8e6989cc3644',
    messagingSenderId: '373194371853',
    projectId: 'project-semester4-ce288',
    authDomain: 'project-semester4-ce288.firebaseapp.com',
    storageBucket: 'project-semester4-ce288.firebasestorage.app',
    measurementId: 'G-S3EGMDMRDZ',
  );

}